# Generated by Django 4.2.11 on 2024-04-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='NN', max_length=45)),
                ('apellido_pat', models.CharField(default='NN', max_length=45)),
                ('apellido_mat', models.CharField(default='NN', max_length=45)),
                ('user_name', models.CharField(default='NN', max_length=45)),
                ('password', models.CharField(default='NN', max_length=45)),
                ('correo', models.CharField(default='NN', max_length=145)),
                ('fecha_naci', models.DateField()),
                ('direccion', models.CharField(default='NN', max_length=150)),
            ],
        ),
    ]
